# Generated by Django 2.2 on 2022-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_auto_20221112_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
    ]
